- hosts: localhost
  tasks:
  - name: "Install all the software"
    become: "{{ should_be_root }}"
    package:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - ripgrep
      - xclip
      - jq
      - tldr
