- hosts: localhost
  tasks:

  - name: Include main vars
    ansible.builtin.include_vars:
      file: vars.yml

  - name: Create work directory
    ansible.builtin.file:
      state: directory
      mode: 'u=rwx,go=rx'
      dest: '~/work/'

  - name: Clone jangl-site
    ansible.builtin.git:
       repo: git@github.com:revpoint/jangl-site.git
       dest: "{{ home }}/work/jangl-site"
       depth: 1
       version: stable

  - name: Run a pull
    ansible.builtin.script:
       chdir: "{{ home }}/work/jangl-site"
       cmd: pull.sh
  
- import_playbook: webleads.yml 
- import_playbook: calls.yml 
