- hosts: localhost
  tasks:

  - name: Include main vars
    ansible.builtin.include_vars:
      file: vars.yml

  - name: Remove old versions of neovim
    ansible.builtin.file:
       path: "{{ home }}/neovim"
       state: absent

  - name: Clone neovim
    ansible.builtin.git:
       repo: https://github.com/neovim/neovim.git
       dest: "{{ home }}/neovim"
       depth: 1
       version: stable

  - name: "Install neovim deps"
    become: "{{ should_be_root }}"
    package:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - cmake
      - gettext

  - name: Build neovim
    ansible.builtin.command: make CMAKE_BUILD_TYPE=RelWithDebInfo
    args:
      chdir: "{{ home }}/neovim"
