- hosts: localhost
  tasks:
    - name: Include main vars
      ansible.builtin.include_vars:
        file: vars.yml

    - name: installing tmux
      become: true
      package:
        name: tmux
        state: present
        update_cache: yes

    - name: install tpm
      ansible.builtin.git:
        repo: "https://github.com/tmux-plugins/tpm" 
        dest: "{{ home }}/.tmux/plugins/tpm"
